name: chatapp
description: こどもがチャットGPTと会話できるようにする
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  flutter_spinkit: ^5.1.0
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  screenshot: ^1.3.0
  share_plus: ^6.3.1
  url_launcher: ^6.1.10
  avatar_glow: ^2.0.2
  draggable_fab: ^0.1.4
  speech_to_text: ^6.1.1
  http: ^0.13.5
  flutter_tts: ^3.6.3
  animated_text_kit: ^4.2.2
  lottie: ^2.3.2
  flutter_slider_drawer: ^2.1.3
  chat_bubbles: ^1.4.1
  babstrap_settings_screen: ^0.1.5+1
  loading_animation_widget: ^1.2.0+4
  settings_ui: ^2.0.2
  select_dialog: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lottie/
  fonts:
    - family: Klasik
      fonts:
        - asset: "assets/fonts/Klasik Regular.otf"
    - family: NotoSansJP-Black
      fonts:
        - asset: "assets/fonts/NotoSansJP-Black.otf"
    - family: NotoSansJP-Medium
      fonts:
        - asset: "assets/fonts/NotoSansJP-Medium.otf"
    - family: NotoSansJP-Regular
      fonts:
        - asset: "assets/fonts/NotoSansJP-Regular.otf"
